openapi: 3.0.1

info:
  title: ecoMobility - Treecko API
  description: API documentation for ecoMobility release v1.0 Treecko.
  version: 1.0.0
  contact:
    name: Mail
    email: ecomobilityupc@gmail.com

servers:
  - url: http://localhost:3001/api/v1/
    description: API v1.0
tags:
  - name: Estaciones
    description: Endpoints para estaciones

paths:
  /estaciones:
    get:
      tags:
        - Estaciones
      summary: Obtener todas las estaciones
      description: Obtener todas las estaciones de la DB con todos sus atributos.
      operationId: getAllEstaciones
      # parameters:
      #   - name: status
      #     in: query
      #     description: Status values that need to be considered for filter
      #     required: false
      #     explode: true
      #     schema:
      #       type: string
      #       default: available
      #       enum:
      #         - available
      #         - pending
      #         - sold
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Estacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                204example:
                  $ref: "#/components/examples/success204"
        "400":
          description: Invalid status value
components:
  schemas:
    Estacion:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          example: 10
        # ACCES:
        #   type:
        #   format:
        #   example: "ESTACIÓ SERVEI"
        # ADREÇA:
        #   type:
        #   format:
        #   example: "Avinguda Meridiana, 666"
        # CODIMUN:
        #   type:
        #   format:
        #   example:
        # CODIPROV:
        #   type:
        #   format:
        #   example:
        # Columna amb georeferència:
        #   type:
        #   format:
        #   example:
        # DESIGNACIÓ-DESCRIPTIVA:
        #   type:
        #   format:
        #   example:
        # INDENTIFICADOR:
        #   type:
        #   format:
        #   example:
        # LATITUD:
        #   type:
        #   format:
        #   example:
        # LONGITUD:
        #   type:
        #   format:
        #   example:
        # MUNICIPI:
        #   type:
        #   format:
        #   example:
        # NPLACES ESTACIÓ:
        #   type:
        #   format:
        #   example:
        # POTENCIA:
        #   type:
        #   format:
        #   example:
        # PROMOTOR-GESTOR:
        #   type:
        #   format:
        #   example:
        # PROVINCIA:
        #   type:
        #   format:
        #   example:
        # TIPUS CONNEXIÓ:
        #   type:
        #   format:
        #   example:
        # TIPUS DE CORRENT:
        #   type:
        #   format:
        #   example:
        # TIPUS VEHICLE:
        #   type:
        #   format:
        #   example:
        # TIPUS VELOCITAT:
        #   type:
        #   format:
        #   example:
    User:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          example: 10
  examples:
    success204:
      value:
        status: 204
        error: "No content"
        message: "No content"
